//reds

  let wines = [{
      name: 'Moraitico Epochi Red',
      code: 'moraitico-epochi-red-2008',
      region: 'Greece > Aegean Islands > Paros',
      winery: 'George Moraitis',
      winery_id: 'george-moraitis',
      varietal: 'Monemvasia (50%); Mandilaria (50%)',
      price: '9.00',
      msrp: '9.53',
      vintage: '2008',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/moraitico-epochi-red-2008/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/9/f/6/image_940065_square.jpeg',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 0
    },
    {
      name: 'Laurel Glen Zinfandel Blend Lodi Reds',
      code: 'laurel-glen-zinfandel-blend-lodi-reds-2007',
      region: 'USA > California > San Joaquin County > Lodi',
      winery: 'Laurel Glen Vineyard',
      winery_id: 'laurel-glen-vineyard',
      varietal: 'Petite Sirah',
      price: '17.72',
      vintage: '2007',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/laurel-glen-zinfandel-blend-lodi-reds-2007/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/6/9/4/image_883989_square.jpeg',
      snoothrank: 3,
      available: 0,
      num_merchants: 0,
      num_reviews: 15
    },
    {
      name: 'Tabor Hill Demi-Red',
      code: 'tabor-hill-demi-red-nv',
      region: 'USA > Michigan > Lake Michigan Shore',
      winery: 'Tabor Hill Winery',
      winery_id: 'tabor-hill-winery',
      varietal: 'Miscellaneous Other',
      price: '9.95',
      msrp: '9.95',
      vintage: 'NV',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/tabor-hill-demi-red-nv/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/9/5/d/image_781003_square.jpeg',
      snoothrank: 4,
      available: 0,
      num_merchants: 0,
      num_reviews: 18
    },
    {
      name: 'Wolf Blass Yellow Label Cabernet Sauvignon Fosters Wine Estates Wines-Australia-Red Table Cabernet Sauvignon',
      code: 'wolf-blass-yellow-label-cabernet-sauvignon-fosters-wine-estates-wines-australia-red-table-cabernet-sauvignon-2004',
      region: 'Australia > South Australia',
      winery: 'Wolf Blass',
      winery_id: 'wolf-blass',
      varietal: 'Cabernet Sauvignon',
      price: '19.19',
      vintage: '2004',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/wolf-blass-yellow-label-cabernet-sauvignon-fosters-wine-estates-wines-australia-red-table-cabernet-sauvignon-2004/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/4/3/d/image_1214913_square.jpeg',
      snoothrank: 3.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 10
    },
    {
      name: 'Joseph Carr Cabernet Sauvignon Napa Valley Red Hills',
      code: 'joseph-carr-cabernet-sauvignon-napa-valley-red-hills-2009',
      region: '',
      winery: 'Joseph Carr',
      winery_id: 'joseph-carr',
      varietal: 'Cabernet Sauvignon (75%); Merlot (15%); Cabernet Franc (10%)',
      price: '0.00',
      vintage: '2009',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/joseph-carr-cabernet-sauvignon-napa-valley-red-hills-2009/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/1/c/9/image_1230443_square.jpeg',
      snoothrank: 3.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 1
    },
    {
      name: 'Xavier Flouret Red Bordeaux Blend Premières Côtes de Blaye la Victoire',
      code: 'xavier-flouret-red-bordeaux-blend-premieres-cotes-de-blaye-la-victoire-2006',
      region: 'France > Bordeaux > Premières Côtes de Blaye',
      winery: 'Le XV du Président',
      winery_id: 'le-xv-du-president',
      varietal: 'Merlot (60%); Cabernet Sauvignon (40%)',
      price: '21.99',
      msrp: '21.99',
      vintage: '2006',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/xavier-flouret-red-bordeaux-blend-premieres-cotes-de-blaye-la-victoire-2006/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/c/2/2/image_780766_square.jpeg',
      snoothrank: 3.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 5
    },
    {
      name: 'Xavier Flouret Red Bordeaux Blend Premières Côtes de Blaye la Victoire ',
      code: 'xavier-flouret-red-bordeaux-blend-premieres-cotes-de-blaye-la-victoire-2008',
      region: 'France > Bordeaux > Premières Côtes de Blaye',
      winery: 'Le XV du Président',
      winery_id: 'le-xv-du-president',
      varietal: 'Merlot (50%); Cabernet Sauvignon (50%)',
      price: '19.00',
      msrp: '19.00',
      vintage: '2008',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/xavier-flouret-red-bordeaux-blend-premieres-cotes-de-blaye-la-victoire-2008/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/b/0/f/image_1098720_square.jpeg',
      snoothrank: 4,
      available: 0,
      num_merchants: 0,
      num_reviews: 3
    },
    {
      name: 'Calcu Red Blend',
      code: 'calcu-red-blend-2008',
      region: 'Chile > Colchagua Valley',
      winery: 'Calcu Winery',
      winery_id: 'calcu-winery',
      varietal: 'Cabernet Sauvignon (45%); Carmenère (25%); Cabernet Franc (15%); Petit Verdot (15%)',
      price: '13.00',
      msrp: '13.00',
      vintage: '2008',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/calcu-red-blend-2008/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/7/a/9/image_1394435_square.jpeg',
      snoothrank: 3,
      available: 0,
      num_merchants: 0,
      num_reviews: 4
    },
    {
      name: 'Sacred Stone Old World Style Red Blend ',
      code: 'sacred-stone-old-world-style-red-blend-nv',
      region: '',
      winery: 'Pietra Santa Winery',
      winery_id: 'pietra-santa-winery',
      varietal: 'Red Blend',
      price: '8.99',
      vintage: 'NV',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/sacred-stone-old-world-style-red-blend-nv/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/2/5/e/image_517368_square.jpeg',
      snoothrank: 3.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 8
    },
    {
      name: 'Red Truck California',
      code: 'red-truck-california-2008',
      region: 'USA > California',
      winery: 'Cline Cellars',
      winery_id: 'cline-cellars',
      varietal: 'Syrah Syrah',
      price: '9.99',
      vintage: '2008',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/red-truck-california-2008/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/7/9/5/image_1235565_square.jpeg',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 10
    },
    {
      name: 'Red Truck California',
      code: 'red-truck-california-2009-1',
      region: 'USA > California',
      winery: 'Cline Cellars',
      winery_id: 'cline-cellars',
      varietal: 'Syrah',
      price: '7.99',
      vintage: '2009',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/red-truck-california-2009-1/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/b/5/3/image_449522_square.jpeg',
      snoothrank: 3,
      available: 0,
      num_merchants: 0,
      num_reviews: 6
    },
    {
      name: 'Emiliana Red Blend Colchagua Valley Gê ',
      code: 'emiliana-red-blend-colchagua-valley-ge-2006',
      region: 'Chile > Colchagua Valley',
      winery: 'Emiliana',
      winery_id: 'emiliana',
      varietal: 'Merlot',
      price: '10.00',
      vintage: '2006',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/emiliana-red-blend-colchagua-valley-ge-2006/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/9/f/b/image_1180773_square.png',
      snoothrank: 2.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 5
    },
    {
      name: 'Emiliana Red Blend Colchagua Valley Gê ',
      code: 'emiliana-red-blend-colchagua-valley-ge-2005',
      region: 'Chile > Colchagua Valley',
      winery: 'Emiliana',
      winery_id: 'emiliana',
      varietal: 'Cabernet Sauvignon^carmenere^s',
      price: '96.29',
      vintage: '2005',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/emiliana-red-blend-colchagua-valley-ge-2005/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/5/e/c/image_450682_square.jpeg',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 10
    },
    {
      name: 'Hermitage Domaine des Remizieres Cuvee Emilie Rhone Marsanne Rhone France Still Red',
      code: 'hermitage-domaine-des-remizieres-cuvee-emilie-rhone-marsanne-rhone-france-still-red-2005',
      region: 'France > Rhône > Northern Rhône > Hermitage',
      winery: 'Domaine des Rémizières',
      winery_id: 'domaine-des-remizieres',
      varietal: 'Marsanne',
      price: '94.95',
      vintage: '2005',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/hermitage-domaine-des-remizieres-cuvee-emilie-rhone-marsanne-rhone-france-still-red-2005/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/d/2/4/image_1194851_square.jpeg',
      snoothrank: 4,
      available: 0,
      num_merchants: 0,
      num_reviews: 11
    },
    {
      name: 'Gundlach Bundschu Red Bordeaux Blend Sonoma Valley Vintage Reserve',
      code: 'gundlach-bundschu-red-bordeaux-blend-sonoma-valley-vintage-reserve-2006',
      region: 'USA > California > Sonoma Valley',
      winery: 'Gundlach Bundschu Winery',
      winery_id: 'gundlach-bundschu-winery',
      varietal: 'Cabernet Sauvignon, Malbec, Petit Verdot',
      price: '80.00',
      msrp: '80.00',
      vintage: '2006',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/gundlach-bundschu-red-bordeaux-blend-sonoma-valley-vintage-reserve-2006/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/7/4/4/image_772483_square.jpeg',
      snoothrank: 4,
      available: 0,
      num_merchants: 0,
      num_reviews: 1
    },
    {
      name: 'Gundlach Bundschu Red Bordeaux Blend Sonoma Valley Vintage Reserve',
      code: 'gundlach-bundschu-red-bordeaux-blend-sonoma-valley-vintage-reserve-2007',
      region: 'USA > California > Sonoma Valley',
      winery: 'Gundlach Bundschu Winery',
      winery_id: 'gundlach-bundschu-winery',
      varietal: 'Cabernet Sauvignon; Petit Verdot; Cabernet Franc; Malbec',
      price: '80.00',
      msrp: '80.00',
      vintage: '2007',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/gundlach-bundschu-red-bordeaux-blend-sonoma-valley-vintage-reserve-2007/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/e/b/4/image_1285090_square.jpeg',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 0
    },
    {
      name: 'Adama Red',
      code: 'adama-red-2008',
      region: 'South Africa',
      winery: 'Bosman Family Vineyards',
      winery_id: 'bosman-family-vineyards',
      varietal: 'Syrah (85%); Mourvèdre (10%); Primitivo (3%); Viogner (2%)',
      price: '17.99',
      msrp: '17.99',
      vintage: '2008',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/adama-red-2008/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/b/7/8/image_997913_square.jpeg',
      snoothrank: 3.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 4
    },
    {
      name: 'Trinitas Red Bordeaux Blend Napa Valley Meritage',
      code: 'trinitas-red-bordeaux-blend-napa-valley-meritage-2008',
      region: 'USA > California > Napa > Oak Knoll',
      winery: 'Trinitas Cellars',
      winery_id: 'trinitas-cellars',
      varietal: '54% Cabernet, 19% Merlot, 17% Cabernet Franc, 10% Malbec   ',
      price: '42.99',
      vintage: '2008',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/trinitas-red-bordeaux-blend-napa-valley-meritage-2008/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/2/a/8/image_849646_square.jpeg',
      snoothrank: 3.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 3
    },
    {
      name: 'Alice White Shiraz Premier Red Shiraz Australia Southeastern Australia',
      code: 'alice-white-shiraz-premier-red-shiraz-australia-southeastern-australia-2009',
      region: 'South East Australia',
      winery: 'Alice White',
      winery_id: 'alice-white',
      varietal: 'Syrah',
      price: '9.99',
      vintage: '2009',
      type: '',
      link: 'http://www.snooth.com/wine/alice-white-shiraz-premier-red-shiraz-australia-southeastern-australia-2009/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/b/4/d/image_2338533_square.png',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 10
    },
    {
      name: 'Marietta Old Vine Red Lot 53',
      code: 'marietta-old-vine-red-lot-53-nv-1',
      region: 'USA > California > Sonoma County',
      winery: 'Marietta Wine Cellars',
      winery_id: 'marietta-wine-cellars',
      varietal: 'Zinfandel',
      price: '13.99',
      vintage: 'NV',
      type: '',
      link: 'http://www.snooth.com/wine/marietta-old-vine-red-lot-53-nv-1/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/e/e/e/image_1222421_square.png',
      snoothrank: 3,
      available: 0,
      num_merchants: 0,
      num_reviews: 14
    },
    //]

    // white argentina
    {
      name: 'Graffigna Pinot Grigio Centenario White',
      code: 'graffigna-pinot-grigio-centenario-white-2012',
      region: 'Argentina > San Juan > Tulum Valley',
      winery: 'Graffigna Wines',
      winery_id: 'graffigna-wines',
      varietal: 'Pinot Grigio',
      price: '14.99',
      vintage: '2012',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/graffigna-pinot-grigio-centenario-white-2012/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/4/5/1/image_2625606_square.jpeg',
      snoothrank: 'n/a',
      available: 1,
      num_merchants: 6,
      num_reviews: 4
    }, {
      name: 'Graffigna Pinot Grigio Centenario White',
      code: 'graffigna-pinot-grigio-centenario-white-2011',
      region: 'Argentina > San Juan > Tulum Valley',
      winery: 'Graffigna Wines',
      winery_id: 'graffigna-wines',
      varietal: 'Pinot Grigio',
      price: '9.99',
      vintage: '2011',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/graffigna-pinot-grigio-centenario-white-2011/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/8/5/4/image_2556759_square.jpeg',
      snoothrank: 3,
      available: 0,
      num_merchants: 0,
      num_reviews: 7
    }, {
      name: 'Xavier Flouret Torrontés Cafayate Flaca',
      code: 'xavier-flouret-torrontes-cafayate-flaca-2009',
      region: 'Argentina > Salta > Cafayate',
      winery: 'Xavier Flouret',
      winery_id: 'xavier-flouret',
      varietal: 'Torrontés is a white Argentine wine grape variety, producing fresh, aromatic wines with moderate acidity,smooth texture and mouthfeel as well as distinctive peach and apricot aromas on the nose.',
      price: '17.00',
      msrp: '17.00',
      vintage: '2009',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/xavier-flouret-torrontes-cafayate-flaca-2009/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/3/1/f/image_1394045_square.jpeg',
      snoothrank: 2.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 2
    }, {
      name: 'Valentin Bianchi White Blend New Age ',
      code: 'valentin-bianchi-white-blend-new-age-nv',
      region: 'Argentina > Mendoza > San Rafael',
      winery: 'Valentin Bianchi',
      winery_id: 'valentin-bianchi',
      varietal: 'Non; varietal White',
      price: '9.49',
      vintage: 'NV',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/valentin-bianchi-white-blend-new-age-nv/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/1/4/6/image_2256533_square.jpeg',
      snoothrank: 4.5,
      available: 1,
      num_merchants: 3,
      num_reviews: 9
    }, {
      name: 'Valentin Bianchi White Blend New Age ',
      code: 'valentin-bianchi-white-blend-new-age-2009',
      region: 'Argentina > Mendoza > San Rafael',
      winery: 'Valentin Bianchi',
      winery_id: 'valentin-bianchi',
      varietal: 'Vermentino',
      price: '7.32',
      vintage: '2009',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/valentin-bianchi-white-blend-new-age-2009/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/c/5/2/image_880096_square.jpeg',
      snoothrank: 4,
      available: 0,
      num_merchants: 0,
      num_reviews: 8
    }, {
      name: 'Valentin Bianchi White Blend New Age ',
      code: 'valentin-bianchi-white-blend-new-age-2010',
      region: 'Argentina > Mendoza > San Rafael',
      winery: 'Valentin Bianchi',
      winery_id: 'valentin-bianchi',
      varietal: 'Non; varietal White',
      price: '9.98',
      vintage: '2010',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/valentin-bianchi-white-blend-new-age-2010/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/f/b/d/image_885099_square.jpeg',
      snoothrank: 3.5,
      available: 1,
      num_merchants: 1,
      num_reviews: 8
    }, {
      name: 'Moët & Chandon Grand Vintage Brut Vintage / 2 Sparkling White France Champagne Chardonnay Pinot Noir Pinot Meunier ',
      code: 'moet-and-chandon-grand-vintage-brut-vintage-2-sparkling-white-france-champagne-chardonnay-pinot-noir-pinot-meunier-2003',
      region: 'Argentina > Rio Negro > Alto Valle de Río Negro',
      winery: 'Karmère Vineyards & Winery',
      winery_id: 'karmere-vineyards-and-winery',
      varietal: 'Pinot Noir',
      price: '27.91',
      vintage: '2003',
      type: 'Sparkling Wine',
      link: 'http://www.snooth.com/wine/moet-and-chandon-grand-vintage-brut-vintage-2-sparkling-white-france-champagne-chardonnay-pinot-noir-pinot-meunier-2003/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/0/5/c/image_3999504_square.jpeg',
      snoothrank: 3.5,
      available: 1,
      num_merchants: 1,
      num_reviews: 16
    }, {
      name: 'Reginato White Blend Blanc de Blancs',
      code: 'reginato-white-blend-blanc-de-blancs-2006',
      region: 'Argentina > Mendoza',
      winery: 'Reginato',
      winery_id: 'reginato',
      varietal: 'Chardonnay',
      price: '15.99',
      vintage: '2006',
      type: 'Sparkling Wine',
      link: 'http://www.snooth.com/wine/reginato-white-blend-blanc-de-blancs-2006/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/2/8/9/image_832403_square.jpeg',
      snoothrank: 3.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 1
    }, {
      name: 'Valentin Bianchi Elsa Chardonnay',
      code: 'valentin-bianchi-elsa-chardonnay-2008',
      region: 'Argentina > Mendoza > San Rafael',
      winery: 'Valentin Bianchi',
      winery_id: 'valentin-bianchi',
      varietal: 'Non; varietal White',
      price: '11.99',
      vintage: '2008',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/valentin-bianchi-elsa-chardonnay-2008/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/e/6/4/image_510519_square.jpeg',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 2
    }, {
      name: 'Bodegas Nieto Senetiner Chardonnay Blend Chardonnay Viognier Don Nicanor',
      code: 'bodegas-nieto-senetiner-chardonnay-blend-chardonnay-viognier-don-nicanor-2008',
      region: 'Argentina > Mendoza > Lujan de Cuyo',
      winery: 'Bodegas Nieto Senetiner',
      winery_id: 'bodegas-nieto-senetiner',
      varietal: 'Non; varietal White',
      price: '10.99',
      vintage: '2008',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/bodegas-nieto-senetiner-chardonnay-blend-chardonnay-viognier-don-nicanor-2008/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/f/8/6/image_783841_square.jpeg',
      snoothrank: 2.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 3
    }, {
      name: 'Bodegas Nieto Senetiner Chardonnay Blend Chardonnay Viognier Don Nicanor',
      code: 'bodegas-nieto-senetiner-chardonnay-blend-chardonnay-viognier-don-nicanor-2007',
      region: 'Argentina > Mendoza > Lujan de Cuyo',
      winery: 'Bodegas Nieto Senetiner',
      winery_id: 'bodegas-nieto-senetiner',
      varietal: 'Non; varietal White',
      price: '14.99',
      vintage: '2007',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/bodegas-nieto-senetiner-chardonnay-blend-chardonnay-viognier-don-nicanor-2007/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/f/8/6/image_783841_square.jpeg',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 1
    }, {
      name: 'La Posta White Blend Cocina Blanco de Blancos',
      code: 'la-posta-white-blend-cocina-blanco-de-blancos-2009',
      region: 'Argentina > Mendoza',
      winery: 'La Posta',
      winery_id: 'la-posta',
      varietal: '',
      price: '19.00',
      vintage: '2009',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/la-posta-white-blend-cocina-blanco-de-blancos-2009/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/1/1/a/image_883578_square.jpeg',
      snoothrank: 3,
      available: 0,
      num_merchants: 0,
      num_reviews: 6
    }, {
      name: 'Amalaya White',
      code: 'amalaya-white-2012',
      region: 'Argentina',
      winery: 'Amalaya',
      winery_id: 'amalaya',
      varietal: 'Other Whites',
      price: '9.99',
      vintage: '2012',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/amalaya-white-2012/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/e/6/7/image_3672906_square.jpeg',
      snoothrank: 'n/a',
      available: 1,
      num_merchants: 3,
      num_reviews: 1
    }, {
      name: 'Zapata White Stones Chardonnay Gualtallary',
      code: 'zapata-white-stones-chardonnay-gualtallary-2012',
      region: 'Argentina > Mendoza',
      winery: 'Catena Alta',
      winery_id: 'catena-alta',
      varietal: 'Chardonnay',
      price: '99.98',
      vintage: '2012',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/zapata-white-stones-chardonnay-gualtallary-2012/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/4/6/7/image_4621373_square.jpeg',
      snoothrank: 3.5,
      available: 1,
      num_merchants: 1,
      num_reviews: 1
    }, {
      name: 'Marcus James Wine White Zinfandel',
      code: 'marcus-james-wine-white-zinfandel-nv',
      region: 'Argentina > Cuyo',
      winery: 'Marcus James',
      winery_id: 'marcus-james',
      varietal: 'Zinfandel',
      price: '8.10',
      vintage: 'NV',
      type: 'Rosé Wine',
      link: 'http://www.snooth.com/wine/marcus-james-wine-white-zinfandel-nv/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/d/d/e/image_880097_square.jpeg',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 2
    }, {
      name: 'Bodega Weinert White Blend Carrascal White',
      code: 'bodega-weinert-white-blend-carrascal-white-2006',
      region: 'Argentina > Mendoza',
      winery: 'Bodega Weinert',
      winery_id: 'bodega-weinert',
      varietal: 'Sauvignon Blanc',
      price: '12.99',
      vintage: '2006',
      type: '',
      link: 'http://www.snooth.com/wine/bodega-weinert-white-blend-carrascal-white-2006/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/8/a/a/image_839389_square.jpeg',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 2
    }, {
      name: 'Graffigna Pinot Grigio Centenario White',
      code: 'graffigna-pinot-grigio-centenario-white-2010-1',
      region: 'Argentina > San Juan',
      winery: 'Graffigna Wines',
      winery_id: 'graffigna-wines',
      varietal: 'Pinot Grigio',
      price: '10.99',
      vintage: '2010',
      type: 'White Wine',
      link: 'http://www.snooth.com/wine/graffigna-pinot-grigio-centenario-white-2010-1/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/a/3/1/image_1311016_square.jpeg',
      snoothrank: 2.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 6
    }, {
      name: 'Catena Zapata Chardonnay Uco Valley Adrianna Vineyard White Stone',
      code: 'catena-zapata-chardonnay-uco-valley-adrianna-vineyard-white-stone-2014',
      region: 'Argentina',
      winery: 'Bodega Catena Zapata',
      winery_id: 'bodega-catena-zapata',
      varietal: 'Chardonnay',
      price: '87.95',
      vintage: '2014',
      type: '',
      link: 'http://www.snooth.com/wine/catena-zapata-chardonnay-uco-valley-adrianna-vineyard-white-stone-2014/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/e/b/f/image_4867469_square.jpeg',
      snoothrank: 'n/a',
      available: 1,
      num_merchants: 1,
      num_reviews: 0
    },
    //]

    {
      name: 'Henri Giraud Esprit Rose France',
      code: 'henri-giraud-esprit-rose-france-nv-1',
      region: 'France',
      winery: 'Henri Giraud',
      winery_id: 'henri-giraud',
      varietal: 'Pinot Noir',
      price: '64.95',
      vintage: 'NV',
      type: 'Sparkling Wine',
      link: 'http://www.snooth.com/wine/henri-giraud-esprit-rose-france-nv-1/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/2/6/c/image_1707745_square.jpeg',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 8
    },
    {
      name: 'Patterson Cellars Rosé Blend Washington Rosé ',
      code: 'patterson-cellars-rose-blend-washington-rose-2009',
      region: 'USA > Washington',
      winery: 'Patterson Cellars',
      winery_id: 'patterson-cellars',
      varietal: 'Cabernet Franc (52%); Syrah (48%)',
      price: '16.00',
      msrp: '16.00',
      vintage: '2009',
      type: 'Rosé Wine',
      link: 'http://www.snooth.com/wine/patterson-cellars-rose-blend-washington-rose-2009/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/6/6/9/image_791350_square.jpeg',
      snoothrank: 2.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 6
    },
    {
      name: 'Château Moyau Rosé Blend Coteaux du Languedoc la Clape',
      code: 'chateau-moyau-rose-blend-coteaux-du-languedoc-la-clape-2007',
      region: 'France > Languedoc-roussillon > Languedoc > Coteaux du Languedoc la Clape',
      winery: 'Chateau Moyau',
      winery_id: 'chateau-moyau',
      varietal: 'Grenache (30%); Cinsault (30%); Syrah (20%); Carignane (20%)',
      price: '16.00',
      msrp: '16.00',
      vintage: '2007',
      type: 'Rosé Wine',
      link: 'http://www.snooth.com/wine/chateau-moyau-rose-blend-coteaux-du-languedoc-la-clape-2007/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/7/f/1/image_623868_square.png',
      snoothrank: 3.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 7
    },
    {
      name: 'Laurent-Perrier Rose Cuvee Alexandra Grand Siecle',
      code: 'laurent-perrier-rose-cuvee-alexandra-grand-siecle-1997',
      region: 'France > Champagne',
      winery: 'Laurent-Perrier',
      winery_id: 'laurent-perrier',
      varietal: 'Pinot Noir; Chardonnay',
      price: '131.77',
      vintage: '1997',
      type: 'Sparkling Wine',
      link: 'http://www.snooth.com/wine/laurent-perrier-rose-cuvee-alexandra-grand-siecle-1997/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/2/4/2/image_230097_square.jpeg',
      snoothrank: 4,
      available: 0,
      num_merchants: 0,
      num_reviews: 10
    },
    {
      name: 'Peconic Bay Winery Merlot North Fork Rosé',
      code: 'peconic-bay-winery-merlot-north-fork-rose-2006',
      region: 'USA > New York > Suffolk County > Long Island > North Fork of Long Island ',
      winery: 'Peconic Bay Winery',
      winery_id: 'peconic-bay-winery',
      varietal: 'Merlot; Chardonnay; Cabernet Franc',
      price: '14.00',
      vintage: '2006',
      type: 'Rosé Wine',
      link: 'http://www.snooth.com/wine/peconic-bay-winery-merlot-north-fork-rose-2006/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/b/4/7/image_309644_square.jpeg',
      snoothrank: 3.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 8
    },
    {
      name: 'Rosé Bordeaux Ac Agneau',
      code: 'rose-bordeaux-ac-agneau-2007',
      region: 'France > Languedoc-roussillon > Languedoc > Vin de Pays Des Côtes du Céressou',
      winery: 'Baron Philippe De Rothschild',
      winery_id: 'baron-philippe-de-rothschild',
      varietal: 'Bordeaux Blend',
      price: '61.98',
      vintage: '2007',
      type: 'Red Wine',
      link: 'http://www.snooth.com/wine/rose-bordeaux-ac-agneau-2007/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/8/2/6/image_1564205_square.jpeg',
      snoothrank: 2.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 3
    },
    {
      name: 'Château Moncontour Rosé Blend Crémant de Loire Brut',
      code: 'chateau-moncontour-rose-blend-cremant-de-loire-brut-2005',
      region: 'France > Loire > Crémant de Loire',
      winery: 'Château Moncontour',
      winery_id: 'chateau-moncontour',
      varietal: 'Chenin Blanc',
      price: '14.99',
      vintage: '2005',
      type: 'Sparkling Wine',
      link: 'http://www.snooth.com/wine/chateau-moncontour-rose-blend-cremant-de-loire-brut-2005/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/7/d/4/image_1211854_square.png',
      snoothrank: 3.5,
      available: 0,
      num_merchants: 0,
      num_reviews: 7
    },
    {
      name: 'Shinn Estate Vineyards Rosé Blend North Fork Rosé',
      code: 'shinn-estate-vineyards-rose-blend-north-fork-rose-2009',
      region: 'USA > New York > Suffolk County > Long Island > North Fork',
      winery: 'Shinn Estate Vineyards',
      winery_id: 'shinn-estate-vineyards',
      varietal: 'Merlot; Cabernet Franc',
      price: '18.99',
      vintage: '2009',
      type: 'Rosé Wine',
      link: 'http://www.snooth.com/wine/shinn-estate-vineyards-rose-blend-north-fork-rose-2009/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/d/c/0/image_956543_square.jpeg',
      snoothrank: 3,
      available: 0,
      num_merchants: 0,
      num_reviews: 11
    },
    {
      name: 'Veuve Clicquot Rose . le Shopping Bagâ',
      code: 'veuve-clicquot-rose-oele-shopping-baga-nv',
      region: 'France > Champagne',
      winery: 'Veuve Clicquot Ponsardin',
      winery_id: 'veuve-clicquot-ponsardin',
      varietal: 'Pinot Noir',
      price: '59.99',
      vintage: 'NV',
      type: '',
      link: 'http://www.snooth.com/wine/veuve-clicquot-rose-oele-shopping-baga-nv/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/c/e/3/image_3255835_square.png',
      snoothrank: 'n/a',
      available: 1,
      num_merchants: 1,
      num_reviews: 18
    },
    {
      name: 'Château d\'Esclans Rosé Blend Côtes de Provence Rosé Whispering Angel',
      code: 'chateau-desclans-rose-blend-cotes-de-provence-rose-whispering-angel-2012',
      region: 'France > Provence > Côtes de Provence',
      winery: 'Domaine des Grands Esclans',
      winery_id: 'domaine-des-grands-esclans',
      varietal: 'Rhone',
      price: '19.99',
      vintage: '2012',
      type: 'Rosé Wine',
      link: 'http://www.snooth.com/wine/chateau-desclans-rose-blend-cotes-de-provence-rose-whispering-angel-2012/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/c/8/9/image_2484214_square.jpeg',
      snoothrank: 3,
      available: 1,
      num_merchants: 4,
      num_reviews: 5
    },
    {
      name: 'Philipponnat Champagne Brut Rose Grand Cru 1522',
      code: 'philipponnat-champagne-brut-rose-grand-cru-1522-2003',
      region: 'France > Champagne',
      winery: 'Philipponnat',
      winery_id: 'philipponnat',
      varietal: 'Champagne',
      price: '108.89',
      vintage: '2003',
      type: 'Sparkling Wine',
      link: 'http://www.snooth.com/wine/philipponnat-champagne-brut-rose-grand-cru-1522-2003/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/b/1/b/image_3083966_square.jpeg',
      snoothrank: 'n/a',
      available: 1,
      num_merchants: 16,
      num_reviews: 0
    },
    {
      name: 'Réserve des Vignerons Cabernet de Saumur Rosé',
      code: 'reserve-des-vignerons-cabernet-de-saumur-rose-2010',
      region: 'France > Loire > Anjou-saumur > Cabernet de Saumur',
      winery: 'Reserve des vignerons',
      winery_id: 'reserve-des-vignerons',
      varietal: 'Cabernet Franc',
      price: '12.99',
      vintage: '2010',
      type: 'Rosé Wine',
      link: 'http://www.snooth.com/wine/reserve-des-vignerons-cabernet-de-saumur-rose-2010/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/1/f/2/image_1954842_square.png',
      snoothrank: 3,
      available: 0,
      num_merchants: 0,
      num_reviews: 11
    },
    {
      name: 'Réserve des Vignerons Cabernet de Saumur Rosé',
      code: 'reserve-des-vignerons-cabernet-de-saumur-rose-2009',
      region: 'France > Loire > Anjou-saumur > Cabernet de Saumur',
      winery: 'Reserve des vignerons',
      winery_id: 'reserve-des-vignerons',
      varietal: 'Cabernet Franc',
      price: '6.99',
      vintage: '2009',
      type: 'Rosé Wine',
      link: 'http://www.snooth.com/wine/reserve-des-vignerons-cabernet-de-saumur-rose-2009/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/5/a/f/image_1191859_square.png',
      snoothrank: 'n/a',
      available: 0,
      num_merchants: 0,
      num_reviews: 8
    },
    {
      name: 'Roger Perrin Vdp Rose',
      code: 'roger-perrin-vdp-rose-2008-1',
      region: 'France > Rhône',
      winery: 'Domaine Roger Perrin',
      winery_id: 'domaine-roger-perrin',
      varietal: '',
      price: '32.00',
      vintage: '2008',
      type: 'Rosé Wine',
      link: 'http://www.snooth.com/wine/roger-perrin-vdp-rose-2008-1/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/3/7/f/image_920884_square.jpeg',
      snoothrank: 3,
      available: 1,
      num_merchants: 1,
      num_reviews: 10
    },
    {
      name: 'Domaine du Jas d\'Esclans Rose',
      code: 'domaine-du-jas-desclans-rose-2009',
      region: 'France > Provence > Côtes de Provence',
      winery: 'Domaine du Jas',
      winery_id: 'domaine-du-jas',
      varietal: 'Grenache',
      price: '12.38',
      vintage: '2009',
      type: '',
      link: 'http://www.snooth.com/wine/domaine-du-jas-desclans-rose-2009/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/9/f/0/image_1099353_square.jpeg',
      snoothrank: 'n/a',
      available: 1,
      num_merchants: 1,
      num_reviews: 2
    },
    {
      name: 'Celebris Rose Extra Brut',
      code: 'celebris-rose-extra-brut-2003',
      region: 'France',
      winery: 'Champagne Gosset',
      winery_id: 'champagne-gosset',
      varietal: 'Pinot Noir; Chardonnay',
      price: '208.64',
      vintage: '2003',
      type: 'Sparkling Wine',
      link: 'http://www.snooth.com/wine/celebris-rose-extra-brut-2003/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/3/c/9/image_790296_square.jpeg',
      snoothrank: 4,
      available: 0,
      num_merchants: 0,
      num_reviews: 9
    },
    {
      name: 'Duval-Leroy Pinot Noir Champagne Brut Rosé',
      code: 'duval-leroy-pinot-noir-champagne-brut-rose-nv',
      region: 'France > Champagne',
      winery: 'Duval-Leroy',
      winery_id: 'duval-leroy',
      varietal: 'Champagne',
      price: '32.99',
      vintage: 'NV',
      type: 'Sparkling Wine',
      link: 'http://www.snooth.com/wine/duval-leroy-pinot-noir-champagne-brut-rose-nv/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/4/8/d/image_245878_square.jpeg',
      snoothrank: 3.5,
      available: 1,
      num_merchants: 1,
      num_reviews: 29
    },
    {
      name: 'Château Grande Cassagne Rosé Blend Costières - de - Nîmes Rosé ',
      code: 'chateau-grande-cassagne-rose-blend-costieres-de-nimes-rose-2009-1',
      region: 'France > Rhône > Costières-de-nîmes',
      winery: 'Château Grande Cassagne',
      winery_id: 'chateau-grande-cassagne',
      varietal: 'Citywinecellar.com',
      price: '8.99',
      vintage: '2009',
      type: 'Rosé Wine',
      link: 'http://www.snooth.com/wine/chateau-grande-cassagne-rose-blend-costieres-de-nimes-rose-2009-1/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/4/b/6/image_941496_square.jpeg',
      snoothrank: 2.5,
      available: 1,
      num_merchants: 1,
      num_reviews: 10
    },
    {
      name: 'Bouvet Brut Rose',
      code: 'bouvet-brut-rose-nv',
      region: 'France > Loire',
      winery: 'Domaine G. et G. Bouvet',
      winery_id: 'domaine-g-et-g-bouvet',
      varietal: 'Chardonnay; Chenin Blanc',
      price: '18.49',
      vintage: 'NV',
      type: 'Sparkling Wine',
      link: 'http://www.snooth.com/wine/bouvet-brut-rose-nv/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/2/7/2/image_197449_square.jpeg',
      snoothrank: 'n/a',
      available: 1,
      num_merchants: 1,
      num_reviews: 6
    },
    {
      name: 'Armand de Brignac Ace of Spades Champagne Rose France',
      code: 'armand-de-brignac-ace-of-spades-champagne-rose-france',
      region: 'France > Lyonnais',
      winery: 'Armand de Brignac Champagne',
      winery_id: 'armand-de-brignac-champagne',
      varietal: 'Champagne',
      price: '449.97',
      vintage: '',
      type: 'Sparkling Wine',
      link: 'http://www.snooth.com/wine/armand-de-brignac-ace-of-spades-champagne-rose-france/',
      tags: '',
      image: 'http://ei.isnooth.com/multimedia/0/9/2/image_1609725_square.jpeg',
      snoothrank: 'n/a',
      available: 1,
      num_merchants: 6,
      num_reviews: 0
    }
  ]

  let countries = {
    Americas: ['United States', 'Argentina', 'Canada', 'El Salvador', 'Puerto Rico'],
    Europe: ['Austria', 'Belgium', 'Denmark', 'Estonia', 'France', 'Germany', 'Great Britain', 'Hungary', 
             'Ireland', 'Italy', 'Malta', 'Netherlands', 'Spain', 'Switzerland', 'United Kingdom', 
             'Norway', 'Poland', 'Portugal', 'Russia' ],
    Asia: ['Hong Kong', 'Japan', 'Malaysia', 'Singapore'],
    Other: ['Australia', 'New Zealand']
  }

module.exports = {wines, countries};